[theme]
primaryColor = "#c0392b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#000000"
font = "sans serif"

[client]
showErrorDetails = true

[server]
headless = true
enableCORS = true
port = 8501
